//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.07 at 05:19:42 PM GMT 
//


package ie.gmit.sw.models;

import java.io.Serializable;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for booking complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="booking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="customer" type="{http://sw.gmit.ie/models/}customer"/>
 *         &lt;element name="vehicle" type="{http://sw.gmit.ie/models/}vehicle"/>
 *         &lt;element name="bookingId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="bookingStartDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="bookingEndDate" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", namespace = "http://sw.gmit.ie/models/", propOrder = {
    "customer",
    "vehicle",
    "bookingId",
    "bookingStartDate",
    "bookingEndDate"
})
@XmlRootElement(name = "booking")
public class Booking implements Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@XmlElement(namespace = "http://sw.gmit.ie/models/", required = true)
    protected Customer customer;
    @XmlElement(namespace = "http://sw.gmit.ie/models/", required = true)
    protected Vehicle vehicle;
    @XmlElement(namespace = "http://sw.gmit.ie/models/")
    protected int bookingId;
    @XmlElement(namespace = "http://sw.gmit.ie/models/", required = true)
    protected String bookingStartDate;
    @XmlElement(namespace = "http://sw.gmit.ie/models/", required = true)
    protected String bookingEndDate;
    
    private List<Booking> bookings = null;

	public Booking() {}
    
    public Booking(Customer customer, Vehicle vehicle, int bookingId, String bookingStartDate, String bookingEndDate) {
		super();
		this.customer = customer;
		this.vehicle = vehicle;
		this.bookingId = bookingId;
		this.bookingStartDate = bookingStartDate;
		this.bookingEndDate = bookingEndDate;
	}

	/**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link Customer }
     *     
     */
    public Customer getCustomer() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Customer }
     *     
     */
    public void setCustomer(Customer value) {
        this.customer = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link Vehicle }
     *     
     */
    public Vehicle getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Vehicle }
     *     
     */
    public void setVehicle(Vehicle value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the bookingId property.
     * 
     */
    public int getBookingId() {
        return bookingId;
    }

    /**
     * Sets the value of the bookingId property.
     * 
     */
    public void setBookingId(int value) {
        this.bookingId = value;
    }

    /**
     * Gets the value of the bookingStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingStartDate() {
        return bookingStartDate;
    }

    /**
     * Sets the value of the bookingStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingStartDate(String value) {
        this.bookingStartDate = value;
    }

    /**
     * Gets the value of the bookingEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBookingEndDate() {
        return bookingEndDate;
    }

    /**
     * Sets the value of the bookingEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBookingEndDate(String value) {
        this.bookingEndDate = value;
    }
    
    @XmlElement(name = "bookings")
    public List<Booking> getBookings() {
		return bookings;
	}

	public void setBookings(List<Booking> bookings) {
		this.bookings = bookings;
	}

}
